var branding = {

    audioOnly               : {disable: true},
    blastDescription        : {disable: true},
    blogDescription         : {disable: true},
    blogName                : {disable: true},
    certificate             : {disable: true},
    communityAutoStart      : {disable: true},
    communitySidecar        : {disable: true},
    communityUrl            : {disable: true, value: "https://igniterealtime.org"},
    country                 : {disable: true},
    credits                 : {disable: false, value: "<a href='https://igniterealtime.org' target='_blank' style='font-size: 16px;'>Pade for Ignite Realtime " + chrome.runtime.getManifest().version + "</a>"},
    desktopShareMode        : {disable: true},
    disableChatButton       : {disable: true},
    domain                  : {disable: true, value: "igniterealtime.org"},
    drawioDescription       : {disable: true},
    embedCommunityChat      : {disable: true},
    enableAVCapture         : {disable: true},
    enableBlast             : {disable: true},
    enableBlog              : {disable: true},
    enableCommunity         : {disable: true},
    enableDrawIO            : {disable: true},
    enableGmail             : {disable: true},
    enableOffice365Business : {disable: true},
    enableOffice365Personal : {disable: true},
    enableOnlyOffice        : {disable: true},
    enableRemoteControl     : {disable: true},
    enableRingtone          : {disable: true},
    enableSip               : {disable: true},
    enableTouchPad          : {disable: true},
    enableVerto             : {disable: true},
    enableWebApps           : {disable: true},
    exten                   : {disable: true},
    language                : {disable: true},
    of365AutoStart          : {disable: true},
    onlyOfficeDescription   : {disable: true},
    onlyOfficeVersion       : {disable: true},
    onlyautosave            : {disable: true},
    onlychat                : {disable: true},
    onlycommentAuthorOnly   : {disable: true},
    onlycomments            : {disable: true},
    onlycompactToolbar      : {disable: true},
    onlyforcesave           : {disable: true},
    onlyheader              : {disable: true},
    onlyleftMenu            : {disable: true},
    onlyrightMenu           : {disable: true},
    onlyshowReviewChanges   : {disable: true},
    onlytoolbar             : {disable: true},
    onlyzoom                : {disable: true},
    phone                   : {disable: true},
    popupWindow             : {disable: true},
    qrcode                  : {disable: true},
    rdpDescription          : {disable: true},
    register                : {disable: true},
    registerIMProtocol      : {disable: true},
    registerMEETProtocol    : {disable: true},
    registerSIPProtocol     : {disable: true},
    registerTELProtocol     : {disable: true},
    registerUrlProtocols    : {disable: true},
    registerXMPPProtocol    : {disable: true},
    remoteConnect           : {disable: true},
    remoteDomain            : {disable: true},
    remoteHost              : {disable: true},
    remotePassword          : {disable: true},
    remoteUsername          : {disable: true},
    role                    : {disable: true},
    saveWinPositions        : {disable: false},
    saveProfile             : {disable: true},
    server                  : {disable: true, value: "igniterealtime.org:443"},
    showOnlyOnlineUsers     : {disable: true},
    showSharedCursor        : {disable: true},
    sipAutoStart            : {disable: true},
    sipDescription          : {disable: true},
    sms                     : {disable: true},
    statusBar               : {disable: true},
    touchPadAutoStart       : {disable: true},
    unregisterUrlProtocols  : {disable: true},
    updateAvatar            : {disable: true},
    uploadApp               : {disable: true},
    uploadAppLabel          : {disable: true},
    uploadAppLabel          : {disable: true},
    uploadAvatar            : {disable: true},
    uploadAvatarLabel       : {disable: true},
    uploadAvatarStatus      : {disable: true},
    uploadStatus            : {disable: true},
    uport                   : {disable: true},
    uportPermission         : {disable: true},
    url                     : {disable: true},
    useClientCert           : {disable: true},
    useCredsMgrApi          : {disable: true, value: false},
    useJabra                : {disable: true},
    useWebsocket            : {disable: true, value: false},
    webApps                 : {disable: true},
    wgNotifications         : {disable: true, value: true},
    useStreamDeck           : {disable: true},
    useTotp                 : {disable: true},
    useUport                : {disable: true},
    useSmartIdCard          : {disable: true},
    useWinSSO               : {disable: true, value: false},
    useBasicAuth            : {disable: true, value: false},
    gmailAccounts           : {disable: true},

    changelog               : {disable: false},
    useMarkdown             : {disable: false, value: true},
    factoryReset            : {disable: false},
    help                    : {disable: false},
    enableInfoPanel         : {disable: false, value: true},
    enableFriendships       : {disable: false},
    email                   : {disable: false},

    enableGooglePay         : {disable: true},
    enablePayPalMe          : {disable: true},
    enableTransferWise      : {disable: true},
    transferWiseKey         : {disable: true},
    useAnonymous            : {disable: false, value: true},
    autoJoinRooms           : {disable: false, value: "open_chat@conference.igniterealtime.org\nopenfire@conference.igniterealtime.org\npade@conference.igniterealtime.org\nsmack@conference.igniterealtime.org"},

    ofmeetUrl               : {disable: true, value: "https://meet.jit.si/"},

    enableRssFeeds          : {disable: false, value: true},
    showRssSummary          : {disable: false, value: false},
    rssAtomFeedUrls         : {disable: false, value: "https://discourse.igniterealtime.org/latest.rss\nhttps://github.com/igniterealtime/Openfire/commits/master.atom"},

    enableBeeKeeper         : {disable: true, value: false},
    beeKeeperTitle          : {disable: true},
    beeKeeperTopic          : {disable: true},
    beeKeeperUrl            : {disable: true},
    beeFeedCheck            : {disable: true},
    beeKeeperPageSize       : {disable: true},
}