var branding = {
    enableBeeKeeper         : {disable: true, value: false},
    beeKeeperTitle          : {disable: true},
    beeKeeperTopic          : {disable: true},
    beeKeeperUrl            : {disable: true},
    beeFeedCheck            : {disable: true},
    beeKeeperPageSize       : {disable: true},
    enableIrma              : {disable: true},
/*
    uport                   : {disable: true},
    uportPermission         : {disable: true},
    useUport                : {disable: true},

    audioOnly               : {disable: true},
    blastDescription        : {disable: true},
    blogDescription         : {disable: true},
    blogName                : {disable: true},
    certificate             : {disable: true},
    changelog               : {disable: false},
    communityAutoStart      : {disable: true},
    communitySidecar        : {disable: true},
    communityUrl            : {disable: true},
    country                 : {disable: true},
    credits                 : {disable: false, value: "<a href='https://desktop-545pc5b:7443/docs' target='_blank' style='font-size: 16px;'>Dele Olajide</a>"},
    disableChatButton       : {disable: true},
    domain                  : {disable: true, value: "desktop-545pc5b"},
    drawioDescription       : {disable: true},
    email                   : {disable: true},
    embedCommunityChat      : {disable: true},
    enableAVCapture         : {disable: true},
    enableBlast             : {disable: true},
    enableBlog              : {disable: true},
    enableCommunity         : {disable: true},
    enableDrawIO            : {disable: true},
    enableGmail             : {disable: true},
    enableOffice365Business : {disable: true},
    enableOffice365Personal : {disable: true},
    enableOnlyOffice        : {disable: true},
    enableRemoteControl     : {disable: true},
    enableRingtone          : {disable: true},
    enableSip               : {disable: true},
    enableTouchPad          : {disable: true},
    enableVerto             : {disable: true},
    enableWebApps           : {disable: true},
    factoryReset            : {disable: false},
    gmailAccounts           : {disable: true},
    help                    : {disable: false},
    language                : {disable: true},
    of365AutoStart          : {disable: true},
    onlyOfficeDescription   : {disable: true},
    onlyOfficeVersion       : {disable: true},
    onlyautosave            : {disable: true},
    onlychat                : {disable: true},
    onlycommentAuthorOnly   : {disable: true},
    onlycomments            : {disable: true},
    onlycompactToolbar      : {disable: true},
    onlyforcesave           : {disable: true},
    onlyheader              : {disable: true},
    onlyleftMenu            : {disable: true},
    onlyrightMenu           : {disable: true},
    onlyshowReviewChanges   : {disable: true},
    onlytoolbar             : {disable: true},
    onlyzoom                : {disable: true},
    phone                   : {disable: true},
    popupWindow             : {disable: true},
    qrcode                  : {disable: true},
    rdpDescription          : {disable: true},
    registerIMProtocol      : {disable: true},
    registerMEETProtocol    : {disable: true},
    registerSIPProtocol     : {disable: true},
    registerTELProtocol     : {disable: true},
    registerUrlProtocols    : {disable: true},
    registerXMPPProtocol    : {disable: true},
    remoteConnect           : {disable: true},
    remoteDomain            : {disable: true},
    remoteHost              : {disable: true},
    remotePassword          : {disable: true},
    remoteUsername          : {disable: true},
    role                    : {disable: true},
    saveWinPositions        : {disable: true},
    server                  : {disable: true, value: "desktop-545pc5b:7443"},
    showOnlyOnlineUsers     : {disable: true},
    showSharedCursor        : {disable: true},
    sipAutoStart            : {disable: true},
    sipDescription          : {disable: true},
    statusBar               : {disable: true},
    touchPadAutoStart       : {disable: true},
    unregisterUrlProtocols  : {disable: true},
    updateAvatar            : {disable: true},
    uploadApp               : {disable: true},
    uploadAppLabel          : {disable: true},
    uploadAppLabel          : {disable: true},
    uploadAvatar            : {disable: true},
    uploadAvatarLabel       : {disable: true},
    uploadAvatarStatus      : {disable: true},
    uploadStatus            : {disable: true},
    url                     : {disable: true},
    useClientCert           : {disable: true},
    useCredsMgrApi          : {disable: true, value: false},
    useJabra                : {disable: true},
    useStreamDeck           : {disable: true},
    useTotp                 : {disable: true},
    useSmartIdCard          : {disable: true},
    useWebsocket            : {disable: true, value: true},
    useWinSSO               : {disable: true, value: false},
    webApps                 : {disable: true},
*/
}