var branding = {

    audioOnly               : {disable: true},
    autoReconnect           : {disable: true, value: true},
    blastDescription        : {disable: true},
    blogDescription         : {disable: true},
    blogName                : {disable: true},
    certificate             : {disable: true},
    changePassword          : {disable: true},
    communityAutoStart      : {disable: true},
    communitySidecar        : {disable: true},
    communityUrl            : {disable: true},
    country                 : {disable: true},
    credits                 : {disable: false},
    desktopShareMode        : {disable: true},
    disableChatButton       : {disable: true},
    domain                  : {disable: false},
    drawioDescription       : {disable: true},
    embedCommunityChat      : {disable: true},
    enableAVCapture         : {disable: true},
    enableBlast             : {disable: true},
    enableBlog              : {disable: true},
    enableCommunity         : {disable: true},
    enableDrawIO            : {disable: true},
    enableGmail             : {disable: true},
    enableOffice365Business : {disable: true},
    enableOffice365Personal : {disable: true},
    enableOnlyOffice        : {disable: true},
    enableRemoteControl     : {disable: true},
    enableRingtone          : {disable: false},
    enableSip               : {disable: true},
    enableTouchPad          : {disable: true},
    enableVerto             : {disable: true},
    enableWebApps           : {disable: true},
    enableInverse           : {disable: true, value: true},
    enableCollaboration     : {disable: true, value: false},
    collabUrlListlabel      : {disable: true},
    updateCollabUrlList     : {disable: true},
    collabUrlList           : {disable: true},
    exten                   : {disable: true},
    language                : {disable: true},
    of365AutoStart          : {disable: true},
    onlyOfficeDescription   : {disable: true},
    onlyOfficeVersion       : {disable: true},
    onlyautosave            : {disable: true},
    onlychat                : {disable: true},
    onlycommentAuthorOnly   : {disable: true},
    onlycomments            : {disable: true},
    onlycompactToolbar      : {disable: true},
    onlyforcesave           : {disable: true},
    onlyheader              : {disable: true},
    onlyleftMenu            : {disable: true},
    onlyrightMenu           : {disable: true},
    onlyshowReviewChanges   : {disable: true},
    onlytoolbar             : {disable: true},
    onlyzoom                : {disable: true},
    openWinMinimized        : {disable: false},
    phone                   : {disable: true},
    popupWindow             : {disable: true},
    qrcode                  : {disable: true},
    rdpDescription          : {disable: true},
    register                : {disable: true},
    registerIMProtocol      : {disable: false},
    registerMEETProtocol    : {disable: false},
    registerSIPProtocol     : {disable: true},
    registerTELProtocol     : {disable: true},
    registerUrlProtocols    : {disable: false},
    registerXMPPProtocol    : {disable: false},
    remoteConnect           : {disable: true},
    remoteDomain            : {disable: true},
    remoteHost              : {disable: true},
    remotePassword          : {disable: true},
    remoteUsername          : {disable: true},
    restartDesc             : {disable: true},
    role                    : {disable: true},
    saveWinPositions        : {disable: false},
    saveProfile             : {disable: true},
    server                  : {disable: false},
    showOnlyOnlineUsers     : {disable: true},
    showSharedCursor        : {disable: true},
    sipAutoStart            : {disable: true},
    sipDescription          : {disable: true},
    sipUseOfSwitch          : {disable: true},
    sms                     : {disable: true},
    statusBar               : {disable: true},
    touchPadAutoStart       : {disable: true},
    unregisterUrlProtocols  : {disable: true},
    updateAvatar            : {disable: true},
    uploadApp               : {disable: true},
    uploadAppLabel          : {disable: true},
    uploadAppLabel          : {disable: true},
    uploadAvatar            : {disable: true},
    uploadAvatarLabel       : {disable: true},
    uploadAvatarStatus      : {disable: true},
    uploadStatus            : {disable: true},
    uport                   : {disable: true},
    uportPermission         : {disable: true},
    url                     : {disable: true},
    useClientCert           : {disable: true},
    useCredsMgrApi          : {disable: true, value: false},
    useJabra                : {disable: true},
    useWebsocket            : {disable: false, value: true},
    webApps                 : {disable: true},
    wgNotifications         : {disable: true, value: true},
    useStreamDeck           : {disable: true},
    useTotp                 : {disable: true},
    useUport                : {disable: true},
    useSmartIdCard          : {disable: true},
    useWinSSO               : {disable: true, value: false},
    useBasicAuth            : {disable: false, value: false},
    useAnonymous            : {disable: false, value: false},
    gmailAccounts           : {disable: true},

    changelog               : {disable: false},
    useMarkdown             : {disable: false, value: true},
    factoryReset            : {disable: false},
    help                    : {disable: false},
    enableInfoPanel         : {disable: false, value: true},
    enableFriendships       : {disable: false},
    email                   : {disable: false},
    hideOfflineUsers        : {disable: false, value: true},
    converseRosterFilter    : {disable: false, value: false},

    enableGooglePay         : {disable: true},
    enablePayPalMe          : {disable: true},
    enableTransferWise      : {disable: true},
    transferWiseKey         : {disable: true},
    autoJoinRooms           : {disable: false},

    ofmeetUrl               : {disable: true, value: "https://meet.jit.si/"},

    enableRssFeeds          : {disable: false, value: true},
    showRssSummary          : {disable: false, value: false},
    rssAtomFeedUrls         : {disable: false},

    enableBeeKeeper         : {disable: true, value: false},
    beeKeeperTitle          : {disable: true},
    beeKeeperTopic          : {disable: true},
    beeKeeperUrl            : {disable: true},
    beeFeedCheck            : {disable: true},
    beeKeeperPageSize       : {disable: true},

    exportPreferences       : {disable: true},
    exportPreferencesDesc   : {disable: true},
    importPreferences       : {disable: true},
    importPreferencesDesc   : {disable: true},
    importExportStatus      : {disable: true},

    enableSignalWire        : {disable: true},
    signalWireSpace         : {disable: true},
    signalWireKey           : {disable: true},
    signalWireId            : {disable: true},
}