// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Woot.IO = (function() {
    function IO(io) {
      this.emit = bind(this.emit, this);
      this.on = bind(this.on, this);
      this.io = io;
    }

    IO.prototype.on = function(msg, data) {
      return this.io.on(msg, data);
    };

    IO.prototype.emit = function(msg, data) {
      return this.io.emit(msg, data);
    };

    return IO;

  })();

}).call(this);
